#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
endpoint_matching.py
====================

Dimension II: backend endpoint matching by shared DNS domains.

Input
-----
A pickle produced by ``flow_preprocessing.py filter``. The input can be:
  - list[dict]
  - pandas.DataFrame

Required flow fields:
  Device, Vendor, Domain

Output
------
1. Pair-level endpoint matches:
   Device1, Vendor1, Device2, Vendor2, Same_Vendor,
   Shared_Domain_Count, Shared_Domains
2. Optional group-level clusters generated by connected components over
   cross-vendor pairs that share at least one domain.
"""

from __future__ import annotations

import argparse
import os
import pickle
from collections import Counter, defaultdict, deque
from itertools import combinations
from typing import Any, Dict, Iterable, List, Sequence, Set, Tuple

import pandas as pd


def load_records(path: str) -> List[Dict[str, Any]]:
    with open(path, "rb") as f:
        obj = pickle.load(f)
    if isinstance(obj, list):
        return obj
    if hasattr(obj, "to_dict"):
        return obj.to_dict(orient="records")
    if isinstance(obj, dict):
        records: List[Dict[str, Any]] = []
        for value in obj.values():
            records.extend(value if isinstance(value, list) else [value])
        return records
    raise ValueError(f"Unsupported pickle format: {type(obj)!r}")


def normalize_domain(value: Any) -> str:
    if value is None:
        return ""
    domain = str(value).strip()
    if domain.lower() in {"", "none", "nan", "null"}:
        return ""
    return domain.rstrip(".").lower()


def build_device_domain_sets(records: Iterable[Dict[str, Any]]) -> Tuple[Dict[str, Set[str]], Dict[str, str]]:
    device_domains: Dict[str, Set[str]] = defaultdict(set)
    device_vendor: Dict[str, str] = {}

    for record in records:
        device = str(record.get("Device", "")).strip()
        if not device:
            continue

        vendor = str(record.get("Vendor", "unknown")).strip() or "unknown"
        domain = normalize_domain(record.get("Domain"))

        device_vendor[device] = vendor
        if domain:
            device_domains[device].add(domain)

    return dict(device_domains), device_vendor


def compute_pair_matches(
    device_domains: Dict[str, Set[str]],
    device_vendor: Dict[str, str],
    min_shared_domains: int = 1,
    cross_vendor_only: bool = False,
) -> List[Dict[str, Any]]:
    devices = sorted(device_domains.keys())
    rows: List[Dict[str, Any]] = []

    for d1, d2 in combinations(devices, 2):
        v1 = device_vendor.get(d1, "unknown")
        v2 = device_vendor.get(d2, "unknown")
        same_vendor = v1.lower() == v2.lower()

        if cross_vendor_only and same_vendor:
            continue

        shared = device_domains[d1] & device_domains[d2]
        if len(shared) < min_shared_domains:
            continue

        rows.append(
            {
                "Device1": d1,
                "Vendor1": v1,
                "Device2": d2,
                "Vendor2": v2,
                "Same_Vendor": same_vendor,
                "Shared_Domain_Count": len(shared),
                "Shared_Domains": "|".join(sorted(shared)),
            }
        )

    rows.sort(key=lambda r: (r["Same_Vendor"], -r["Shared_Domain_Count"], r["Device1"], r["Device2"]))
    return rows


def build_domain_groups(pair_rows: Sequence[Dict[str, Any]]) -> pd.DataFrame:
    """
    Convert pair matches into connected components.

    A component is built from cross-vendor shared-domain edges. The output is
    useful as the Dimension II group file consumed by corroboration.
    """
    graph: Dict[str, Set[str]] = defaultdict(set)
    device_vendor: Dict[str, str] = {}
    edge_domains: Dict[Tuple[str, str], Set[str]] = {}

    for row in pair_rows:
        if bool(row.get("Same_Vendor")):
            continue
        d1, d2 = row["Device1"], row["Device2"]
        graph[d1].add(d2)
        graph[d2].add(d1)
        device_vendor[d1] = row.get("Vendor1", "unknown")
        device_vendor[d2] = row.get("Vendor2", "unknown")
        edge_domains[tuple(sorted((d1, d2)))] = set(str(row.get("Shared_Domains", "")).split("|"))

    seen: Set[str] = set()
    groups: List[Dict[str, Any]] = []
    group_id = 0

    for start in sorted(graph):
        if start in seen:
            continue
        queue = deque([start])
        seen.add(start)
        component: Set[str] = set()

        while queue:
            node = queue.popleft()
            component.add(node)
            for nb in graph[node]:
                if nb not in seen:
                    seen.add(nb)
                    queue.append(nb)

        if len(component) < 2:
            continue

        domains: Set[str] = set()
        for d1, d2 in combinations(sorted(component), 2):
            domains.update(edge_domains.get(tuple(sorted((d1, d2))), set()))

        vendors = sorted({device_vendor.get(d, "unknown") for d in component})
        group_id += 1
        groups.append(
            {
                "Cluster_ID": f"D2_{group_id:04d}",
                "Num_Devices": len(component),
                "Num_Vendors": len(set(v.lower() for v in vendors)),
                "Devices": "|".join(sorted(component)),
                "Vendors": "|".join(vendors),
                "Shared_Domains": "|".join(sorted(d for d in domains if d)),
                "Shared_Domain_Count": len([d for d in domains if d]),
            }
        )

    return pd.DataFrame(groups)


def write_summary(path: str, pair_rows: Sequence[Dict[str, Any]], device_domains: Dict[str, Set[str]]) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    cross_vendor = [r for r in pair_rows if not bool(r["Same_Vendor"])]
    same_vendor = [r for r in pair_rows if bool(r["Same_Vendor"])]

    domain_pair_count = Counter()
    for row in pair_rows:
        for domain in str(row.get("Shared_Domains", "")).split("|"):
            if domain:
                domain_pair_count[domain] += 1

    lines = []
    lines.append("=" * 60)
    lines.append("Endpoint matching summary")
    lines.append("=" * 60)
    lines.append(f"Devices with DNS domains       : {len(device_domains):,}")
    lines.append(f"Unique domains                 : {len(set().union(*device_domains.values())) if device_domains else 0:,}")
    lines.append(f"Pairs with shared domains      : {len(pair_rows):,}")
    lines.append(f"  Cross-vendor pairs           : {len(cross_vendor):,}")
    lines.append(f"  Same-vendor pairs            : {len(same_vendor):,}")
    lines.append("")
    lines.append("Top shared domains:")
    for domain, count in domain_pair_count.most_common(20):
        lines.append(f"  {domain:<60} {count:>6}")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def run_endpoint_matching(
    input_pickle: str,
    pair_output_csv: str,
    summary_output_txt: str | None = None,
    group_output_csv: str | None = None,
    min_shared_domains: int = 1,
    cross_vendor_only: bool = False,
) -> None:
    records = load_records(input_pickle)
    device_domains, device_vendor = build_device_domain_sets(records)
    pair_rows = compute_pair_matches(
        device_domains,
        device_vendor,
        min_shared_domains=min_shared_domains,
        cross_vendor_only=cross_vendor_only,
    )

    os.makedirs(os.path.dirname(pair_output_csv) or ".", exist_ok=True)
    pd.DataFrame(pair_rows).to_csv(pair_output_csv, index=False, encoding="utf-8-sig")

    if summary_output_txt:
        write_summary(summary_output_txt, pair_rows, device_domains)

    if group_output_csv:
        group_df = build_domain_groups(pair_rows)
        os.makedirs(os.path.dirname(group_output_csv) or ".", exist_ok=True)
        group_df.to_csv(group_output_csv, index=False, encoding="utf-8-sig")

    print(f"[+] pairs : {len(pair_rows):,} -> {pair_output_csv}")
    if group_output_csv:
        print(f"[+] groups: {len(pd.read_csv(group_output_csv)):,} -> {group_output_csv}")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Dimension II endpoint matching by shared domains.")
    parser.add_argument("--input-pickle", required=True)
    parser.add_argument("--pair-output-csv", required=True)
    parser.add_argument("--summary-output-txt", default=None)
    parser.add_argument("--group-output-csv", default=None)
    parser.add_argument("--min-shared-domains", type=int, default=1)
    parser.add_argument("--cross-vendor-only", action="store_true")
    return parser


def main() -> None:
    args = build_parser().parse_args()
    run_endpoint_matching(
        input_pickle=args.input_pickle,
        pair_output_csv=args.pair_output_csv,
        summary_output_txt=args.summary_output_txt,
        group_output_csv=args.group_output_csv,
        min_shared_domains=args.min_shared_domains,
        cross_vendor_only=args.cross_vendor_only,
    )


if __name__ == "__main__":
    main()
